### ISSUE TITLE
Par vārdnīcām

### ISSUE THREAD

**Issue by zirneklitis** [WARP-LAB/Pareizrakstiba-Archive#1]
Sveicināti,

Ir iecere mazliet pielabot, papildināt un pārveidot citos formātos Tevis apkopotās vārdnīcas (http://www.krokoarch.lv/mac/en/vardnicas/). Tādēļ ir vairāki jautājumi:
1. Man kā neMAC lietotājam vārdnīcas pieejamas StarDict formātā. (vismaz ātrumā neizdevās ārpus Maka atrast neko, kas saprastu vārdnīcas failus, kuri domāti Makam). Uzģenerētie StarDict formāta faili ir ar pāris tehniskiem defektiem, kurus var viegli novērst. Jautājums drīzāk ir domājot par dažu saturisku labojumu ieviešanu. Vai ir pieejams šo vārdnīcu izejas fails, jeb par tādu uzskatīt StarDict formāta failu?
2. Kāda ir šo vārdnīcu izcelsme (no augšminētās mājas lapas tas nav saprotams) un vai _tiešām_ uz viņām var attiecināt GPL.
3. Ja vārdnīcas tiešam ir atļauts izplatīt ar GPL, tad jautājums, vai piemērotāka nav kāda no CC licencēm?

Cerot uz sadarbību,
Kārlis (eko pie lanet lv)

**Comment by kroko** [comment]
Sveicināts,

---

Ja nemaldos, tad LV-EN, EN-LV, LV-RU, RU-LV un eirožargona vārdnīcas tika iegūtas, izmantojot Babylon vārdnīcas.
http://www.babylon.com/free-dictionaries/languages/latvian/
http://www.babylon.com/free-dictionaries/EUROJARGON_-_latviešu_valoda/47955/Č/1
Par vācu un sinonīmu vārdnīcām es tagad neatminos, šķiet jau bija stardict formātā.
Tātad - kā izejas faili uzskatāmi mikslis no BGL un stardict.

---

Kas saistās ar Babylon izcelsmi - tā ir norādīta footerī.
LV-EN, EN-LV, LV-RU, RU-LV --- may
Eirožargons --- EUROPA: portal site of the European Union

Rakstīju Babylon par šo, un atbilde bija:

Dear Kroko!
Thank you for taking the time writing to us.
With a Babylon license you may use all Babylon dictionaries and free public dictionaries without any further license.
Premium Content dictionaries will need an additional license.
You are welcome to search through Babylon Index for any glossaries which will fit your needs.
Please use the following links:
All Babylon Glossaries and Free Public glossaries are located at : http://www.babylon.com/gloss/glossaries.html
All Premium Content Dictionaries (require a separate license) are located at: http://www.babylon.com/display.php?id=130&tree=3&level=2
In order to add a dictionary, either subscribe to it for online results, or download and install it for offline use.
Anna Diemers
Customer Relations Team
Babylon Ltd.

Es lietoju brīvās vārdnīcas no http://www.babylon.com/gloss/glossaries.html, nav licences.

Tālāk jāskata citāts no Babylon.com
Proprietary Rights to Information and Data
The information and data provided by or through the Service is protected by international copyright laws of Babylon, its third party providers, or any other User that posts information on the Website. The User acknowledges that such information and data may contain other proprietary information and material, and the User will respect all such proprietary rights and take such precautions as may be reasonably necessary to protect private, confidential and other proprietary information and material from unauthorized use..

Attiecīgi tad nu ir:
Latviešu-English, English-Latviešu, Latviešu - Русский, Русский - Latviešu © may
Latviešu eirožargons © EUROPA: portal site of the European Union

Nekas nav minēts par to konvertēšanu.
Turklāt te ir ir tā mistika, ka kamēr no vienas puses Babylon vārdnīcas ir par brīvu, tomēr viņi min, ka var būt tomēr kaut kādas autortiesības. Ok, © arī ir minēti pie šīm vārdnīcām, tomēr šie divi kompilatori nav norādījuši nekādus licencēšanas noteikumus, tādēļ vienkārši saglabāju viņu © kā referenci uz oriģinālo autorību, bet bliežu tālāk.
Turklāt, may un EUROPA: portal site of the European Union, izvietojot šīs vārdnīcas babylon.com, ir piekrituši citiem noteikumiem, kas garantē vārdnīcu materiālu leģitimitāti. T.i., to, ka viņi vai nu ir pirmavoti vai arī, ja nu viņi ir izmantojuši paši kādu avotu, kompilējot vārdnīcas pirms to ievietošanas Babylon, nav pārkāpuši autortiesības. Pirm-pirmaavots ir viņu atbildība un es to nevaru pārbaudīt, tikai uzticēties.

---

Tā kā vienīgā lieta, kas mani uztrauca, ir lai šīs vārdnīcas turpinātu būt par brīvu un iespējamie to papildinājumi arī, toreiz vienkārši piemetu klāt GPL. Pirms tiem n-tajiem gadiem CC licences nebija tik populāras. Un, jā, GPL vispār ir ar arī saviem mīnusiem. Lai nu kā, Babylon gadījumā vispār it kā nav licences, saglabāju to (c) un pieliku GPL birku. Turklāt tas, vai "may" ir cilvēks vai robots, ... 

1) Par izeju uzskati stardict
2) Skat augstāk
3) Šobrīd nav viedokļa.
